name: Build Release Images

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Package Manager
      run: sudo apt update
    - name: Install Dependencies
      run: |
        sudo apt install build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools python3-dev rsync subversion swig time \
        xsltproc zlib1g-dev wget
    - name: Install Root Certificates
      run: |
        sudo apt-get install --reinstall ca-certificates
        sudo mkdir /usr/local/share/ca-certificates/cacert.org
        sudo wget -P /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt
        sudo update-ca-certificates
        git config --global http.sslCAinfo /etc/ssl/certs/ca-certificates.crt
    - name: Update Feeds
      run: ./scripts/feeds update
    - name: Install Lua Sockets
      run: ./scripts/feeds install luasocket
    - name: Copy Config
      run: cp FRC-config .config
    - name: Build OpenWRT
      run: make -j$(nproc)
    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        asset_name: nevermore-fimware-om5p-ac.bin
        file: bin/targets/ar71xx/generic/openwrt-ar71xx-generic-om5pac-squashfs-factory.bin
        tag: ${{ github.ref }}
