name: Build Nightly Images

on:
  push:
    branches: [ nevermore ]
  pull_request:
    branches: [ nevermore ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Package Manager
      run: sudo apt update
    - name: Install Dependencies
      run: |
        sudo apt install build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools python3-dev rsync subversion swig time \
        xsltproc zlib1g-dev
    - name: Copy Config
      run: cp OM5P-AC.config .config
    - name: Build OpenWRT
      run: make -j$(nproc)
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: nevermore-fimware-om5p-ac-v2.bin
        path: bin/targets/ath79/generic/openwrt-ath79-generic-openmesh_om5p-ac-v2-squashfs-sysupgrade.bin
